# Generated by Django 4.2 on 2023-04-24 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(verbose_name='original url')),
                ('short_code', models.CharField(max_length=20, unique=True, verbose_name='short code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number_of_transitions', models.PositiveIntegerField(default=0, verbose_name='number of transitions')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='short_urls', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
